### ISSUE TITLE
Question: Why is pip-licenses considered to be part of system packages?

### ISSUE THREAD

**Issue by fredrikbondesson** [raimon49/pip-licenses#117]
I have noticed that pip-licenses (as well as PTable) is considered to be part of the system packages, at least the --with-system argument is needed to show corresponding license information.

I am not sure I understand the reason for this?
For me it is a tool that I have added to my requirements file as many other tools. Then when I am trying to gather license information, I definitely would like it to show up in the normal(non system) list.

Thanks for providing a very useful tool
Regards Fredrik

**Comment by johnthagen** [comment]
I personally think the way this works currently is more accurate. I use `pip-licenses` to make a license report of my *actual* requirements (not `dev-requirements`, etc.) The only way for `pip-licenses` to do this is to be installed into the same environment. I'm not distributing or actually depending on `pip-licenses` at runtime (and I doubt many apps would?), it's simply a tool to generate the license report.

This is very similar to the other system packages, like `pip`. My application at runtime doesn't depend on it, but it has to be in the environment so that the other dependencies can be reported (by installing `pip-licenses`.

Perhaps there should be a way to opt-in to including `pip-licenses` and `PTable`? But I personally think the current behavior should remain the default.

**Comment by raimon49** [comment]
@johnthagen @fredrikbondesson I do not intend to change the behavior as system packages for now.

However, it is good that this behavior is clearly documented. I've just added it to the README document.

Thanks for the good discussion!
